#!/bin/bash

port=1212

base_dir="$(dirname "$0")"

android_target=aarch64-linux-android
run_variant=release
build_dir="$base_dir/target/$android_target/$run_variant"

./build-rust
adb push "$build_dir"/tcp-android /data/local/tmp
adb shell /data/local/tmp/tcp-android "$port"
