#!/bin/bash

set -e

if [ $# -ne 2 ]; then
  echo 'Usage: Command <adb-src-dir> <dest-dir>'
  exit 1
fi

function android_mktemp() {
    adb shell mktemp "$@"
}

base_dir="$(dirname "$0")"

android_build_dir="$base_dir"/target/aarch64-linux-android/debug
build_dir="$base_dir"/target/debug

src_dir="$1"
dest_path="$2"

entry_list_file="$(mktemp)"
send_list_file="$(mktemp)"

android_bin_dir="$(android_mktemp -d)"

adb push "$android_build_dir/index" "$android_bin_dir"
adb push "$android_build_dir/send" "$android_bin_dir"

# debug
# entry_list_file=./entry-list
# send_list_file=./send-list

echo 'Indexing Android files...'
adb shell "$android_bin_dir/index" "$src_dir" > "$entry_list_file" && echo
echo 'Generating send list...'
"$build_dir/diff" "$entry_list_file" "$dest_path" > "$send_list_file" && echo
echo 'Sending tar-zst...'
adb shell "$android_bin_dir/send" "$src_dir" < "$send_list_file" \
  | pv \
  | zstd -d \
  | "$build_dir/receive" "$dest_path" && echo Done

