#!/bin/bash

set -e
set -o pipefail

if [ $# -ne 3 ]; then
  echo 'Usage: Command <address> <android-dir> <dest-dir>'
  exit 1
fi

base_dir="$(dirname "$0")"

run_variant=release
build_dir="$base_dir"/target/$run_variant

address="$1"
src_dir="$2"
dest_path="$3"

# Like rsync, if src_dir ends with a slash, use a directory with the same name as src_dir and
# later the synced files are under it.
synced_dest="$dest_path"
echo "$src_dir" | rg '.*[^/]$' >/dev/null && synced_dest="$dest_path/$(basename "$src_dir")" && (mkdir "$synced_dest" 2>/dev/null || true)

"$build_dir"/tcp-host "$address" "$src_dir" "$synced_dest"
