#!/bin/bash

set -e

if [ $# -eq 0 ]; then
  echo 'Usage: Command <adb-src-dir> <dest-dir>'
  exit 1
fi

src_dir="$1"
dest_path="$2"
parent_path="$(dirname "$src_dir")"
base_name="$(basename "$src_dir")"

mtime_list_file="$(mktemp)"
diff_list_file="$(mktemp)"

# debug
# mtime_list_file=./mtime-list
# diff_list_file=./diff-list

