#!/bin/bash

flag=-r
android_target=aarch64-linux-android

RUSTFLAGS="-C link-arg=-s" cargo build $flag --manifest-path=adb-sync-android/Cargo.toml --target "$android_target"
RUSTFLAGS="-C link-arg=-s" cargo build $flag